DROP TABLE just_conn_test_table;
DROP TABLE t1;
DROP TABLE t2;
DROP TABLE smallint_test;
DROP TABLE smallint_test_err;
DROP TABLE integer_test;
DROP TABLE integer_test_err;
DROP TABLE bigint_test;
DROP TABLE bigint_test_err;
DROP TABLE r_and_dp_test;
DROP TABLE t3;
DROP TABLE t4 ;
DROP TABLE ft_test ;
DROP TABLE vt1;
DROP TABLE jt1;
DROP TABLE st1 ;
DROP TABLE st2 ;
DROP TABLE t_test1;
DROP TABLE t_test2;
DROP TABLE t_test3;
DROP TABLE syn_test ;
DROP TABLE null_test_table;
DROP TABLE math_func_test_table;
DROP SYNONYM ex_syn;
DROP VIEW v_test;
