BEGIN
	BEGIN
		EXECUTE IMMEDIATE 'DROP TABLE just_conn_test_table';
		EXCEPTION
			WHEN OTHERS THEN
				NULL;
	END;

	BEGIN
		EXECUTE IMMEDIATE 'DROP TABLE t1';
		EXCEPTION
			WHEN OTHERS THEN
				NULL;
	END;

	BEGIN
		EXECUTE IMMEDIATE 'DROP TABLE t2';
		EXCEPTION
			WHEN OTHERS THEN
				NULL;
	END;

	BEGIN
		EXECUTE IMMEDIATE 'DROP TABLE smallint_test';
		EXCEPTION
			WHEN OTHERS THEN
				NULL;
	END;

	BEGIN
		EXECUTE IMMEDIATE 'DROP TABLE smallint_test_err';
		EXCEPTION
			WHEN OTHERS THEN
				NULL;
	END;

	BEGIN
		EXECUTE IMMEDIATE 'DROP TABLE integer_test';
		EXCEPTION
			WHEN OTHERS THEN
				NULL;
	END;

	BEGIN
		EXECUTE IMMEDIATE 'DROP TABLE integer_test_err';
		EXCEPTION
			WHEN OTHERS THEN
				NULL;
	END;

	BEGIN
		EXECUTE IMMEDIATE 'DROP TABLE bigint_test';
		EXCEPTION
			WHEN OTHERS THEN
				NULL;
	END;

	BEGIN
		EXECUTE IMMEDIATE 'DROP TABLE bigint_test_err';
		EXCEPTION
			WHEN OTHERS THEN
				NULL;
	END;

	BEGIN
		EXECUTE IMMEDIATE 'DROP TABLE r_and_dp_test';
		EXCEPTION
			WHEN OTHERS THEN
				NULL;
	END;

	BEGIN
		EXECUTE IMMEDIATE 'DROP TABLE t3';
		EXCEPTION
			WHEN OTHERS THEN
				NULL;
	END;

	BEGIN
		EXECUTE IMMEDIATE 'DROP TABLE t4';
		EXCEPTION
			WHEN OTHERS THEN
				NULL;
	END;

	BEGIN
		EXECUTE IMMEDIATE 'DROP TABLE ft_test';
		EXCEPTION
			WHEN OTHERS THEN
				NULL;
	END;

	BEGIN
		EXECUTE IMMEDIATE 'DROP TABLE vt1';
		EXCEPTION
			WHEN OTHERS THEN
				NULL;
	END;

	BEGIN
		EXECUTE IMMEDIATE 'DROP TABLE jt1';
		EXCEPTION
			WHEN OTHERS THEN
				NULL;
	END;

	BEGIN
		EXECUTE IMMEDIATE 'DROP TABLE st1';
		EXCEPTION
			WHEN OTHERS THEN
				NULL;
	END;

	BEGIN
		EXECUTE IMMEDIATE 'DROP TABLE st2';
		EXCEPTION
			WHEN OTHERS THEN
				NULL;
	END;

	BEGIN
		EXECUTE IMMEDIATE 'DROP TABLE t_test1';
		EXCEPTION
			WHEN OTHERS THEN
				NULL;
	END;

	BEGIN
		EXECUTE IMMEDIATE 'DROP TABLE t_test2';
		EXCEPTION
			WHEN OTHERS THEN
				NULL;
	END;

	BEGIN
		EXECUTE IMMEDIATE 'DROP TABLE t_test3';
		EXCEPTION
			WHEN OTHERS THEN
				NULL;
	END;

	BEGIN
		EXECUTE IMMEDIATE 'DROP TABLE syn_test ';
		EXCEPTION
			WHEN OTHERS THEN
				NULL;
	END;

	BEGIN
		EXECUTE IMMEDIATE 'DROP TABLE null_test_table';
		EXCEPTION
			WHEN OTHERS THEN
				NULL;
	END;

	BEGIN
		EXECUTE IMMEDIATE 'DROP TABLE math_func_test_table';
		EXCEPTION
			WHEN OTHERS THEN
				NULL;
	END;

	BEGIN
		EXECUTE IMMEDIATE 'DROP SYNONYM ex_syn';
		EXCEPTION
			WHEN OTHERS THEN
				NULL;
	END;

	BEGIN
		EXECUTE IMMEDIATE 'DROP VIEW v_test';
		EXCEPTION
			WHEN OTHERS THEN
				NULL;
	END;

	BEGIN
		EXECUTE IMMEDIATE 'DROP TABLE INS_TEST';
		EXCEPTION
			WHEN OTHERS THEN
				NULL;
	END;
END;
