-- Start transaction and plan the tests.
BEGIN;
  CREATE EXTENSION IF NOT EXISTS pgtap;

  SELECT plan(10);

  CREATE EXTENSION IF NOT EXISTS tibero_fdw;

  CREATE SERVER server_name FOREIGN DATA WRAPPER tibero_fdw
    OPTIONS (host :TIBERO_HOST, port :TIBERO_PORT, dbname :TIBERO_DB);

  CREATE USER MAPPING FOR current_user
    SERVER server_name
    OPTIONS (username :TIBERO_USER, password :TIBERO_PASS);

  CREATE FOREIGN TABLE string_test_table (
      c_kor CHAR(100),
      c_eng CHAR(100),
      c_spc CHAR(100),
      c_kor_full CHAR(2000),
      c_eng_full CHAR(2000),
      c_spc_full CHAR(2000),
      nc_kor NCHAR(100),
      nc_eng NCHAR(100),
      nc_spc NCHAR(100),
      nc_kor_full NCHAR(2000),
      nc_eng_full NCHAR(2000),
      nc_spc_full NCHAR(2000),
      vc_kor VARCHAR(100),
      vc_eng VARCHAR(100),
      vc_spc VARCHAR(100),
      vc_kor_full VARCHAR(65532),
      vc_eng_full VARCHAR(65532),
      vc_spc_full VARCHAR(65532),
      vc2_kor VARCHAR(100),
      vc2_eng VARCHAR(100),
      vc2_spc VARCHAR(100),
      vc2_kor_full VARCHAR(65532),
      vc2_eng_full VARCHAR(65532),
      vc2_spc_full VARCHAR(65532),
      nvc_kor TEXT,
      nvc_eng TEXT,
      nvc_spc TEXT,
      nvc_kor_full TEXT,
      nvc_eng_full TEXT,
      nvc_spc_full TEXT,
      nvc2_kor TEXT,
      nvc2_eng TEXT,
      nvc2_spc TEXT,
      nvc2_kor_full TEXT,
      nvc2_eng_full TEXT,
      nvc2_spc_full TEXT
  ) SERVER server_name OPTIONS (owner_name 'tibero', table_name 't1');

  -- TEST 1: 문자열 Concatenate (||) 함수
  SELECT results_eq('
    SELECT c_kor || c_eng || c_spc || c_kor_full || c_eng_full || c_spc_full || nc_kor || nc_eng ||
  nc_spc || nc_kor_full || nc_eng_full || nc_spc_full || vc_kor || vc_eng || vc_spc ||
  vc_kor_full || vc_eng_full || vc_spc_full || vc2_kor || vc2_eng || vc2_spc || vc2_kor_full ||
  vc2_eng_full || vc2_spc_full || nvc_kor || nvc_eng || nvc_spc || nvc_kor_full || nvc_eng_full ||
  nvc_spc_full || nvc2_kor || nvc2_eng || nvc2_spc ||
  nvc2_kor_full || nvc2_eng_full || nvc2_spc_full
FROM string_test_table',
    $$VALUES (
      '가a!가나다라마바사아자차카타파하abcdefghijklmnopqrstuvwxyz!@#$%^&*()<>/\\''가a!가나다라마바사아자차카타파하abcdefghijklmnopqrstuvwxyz!@#$%^&*()<>/\\''가a!가나다라마바사아자차카타파하abcdefghijklmnopqrstuvwxyz!@#$%^&*()<>/\\''가a!가나다라마바사아자차카타파하abcdefghijklmnopqrstuvwxyz!@#$%^&*()<>/\\''가a!가나다라마바사아자차카타파하abcdefghijklmnopqrstuvwxyz!@#$%^&*()<>/\\''가a!가나다라마바사아자차카타파하abcdefghijklmnopqrstuvwxyz!@#$%^&*()<>/\\'''::TEXT)
    $$
  );

  -- TEST 2: bit_length() 함수
  SELECT results_eq('
    SELECT
      bit_length(c_kor),
      bit_length(c_eng),
      bit_length(c_spc),
      bit_length(c_kor_full),
      bit_length(c_eng_full),
      bit_length(c_spc_full),
      bit_length(nc_kor),
      bit_length(nc_eng),
      bit_length(nc_spc),
      bit_length(nc_kor_full),
      bit_length(nc_eng_full),
      bit_length(nc_spc_full),
      bit_length(vc_kor),
      bit_length(vc_eng),
      bit_length(vc_spc),
      bit_length(vc_kor_full),
      bit_length(vc_eng_full),
      bit_length(vc_spc_full),
      bit_length(vc2_kor),
      bit_length(vc2_eng),
      bit_length(vc2_spc),
      bit_length(vc2_kor_full),
      bit_length(vc2_eng_full),
      bit_length(vc2_spc_full),
      bit_length(nvc_kor),
      bit_length(nvc_eng),
      bit_length(nvc_spc),
      bit_length(nvc_kor_full),
      bit_length(nvc_eng_full),
      bit_length(nvc_spc_full),
      bit_length(nvc2_kor),
      bit_length(nvc2_eng),
      bit_length(nvc2_spc),
      bit_length(nvc2_kor_full),
      bit_length(nvc2_eng_full),
      bit_length(nvc2_spc_full)
    FROM string_test_table',
    $$VALUES (
      24::INTEGER,
      8::INTEGER,
      8::INTEGER,
      336::INTEGER,
      208::INTEGER,
      128::INTEGER,
      24::INTEGER,
      8::INTEGER,
      8::INTEGER,
      336::INTEGER,
      208::INTEGER,
      128::INTEGER,
      24::INTEGER,
      8::INTEGER,
      8::INTEGER,
      336::INTEGER,
      208::INTEGER,
      128::INTEGER,
      24::INTEGER,
      8::INTEGER,
      8::INTEGER,
      336::INTEGER,
      208::INTEGER,
      128::INTEGER,
      24::INTEGER,
      8::INTEGER,
      8::INTEGER,
      336::INTEGER,
      208::INTEGER,
      128::INTEGER,
      24::INTEGER,
      8::INTEGER,
      8::INTEGER,
      336::INTEGER,
      208::INTEGER,
      128::INTEGER)
    $$
  );

  -- TEST 3: char_length() 함수
  SELECT results_eq('
    SELECT
      char_length(c_kor),
      char_length(c_eng),
      char_length(c_spc),
      char_length(c_kor_full),
      char_length(c_eng_full),
      char_length(c_spc_full),
      char_length(nc_kor),
      char_length(nc_eng),
      char_length(nc_spc),
      char_length(nc_kor_full),
      char_length(nc_eng_full),
      char_length(nc_spc_full),
      char_length(vc_kor),
      char_length(vc_eng),
      char_length(vc_spc),
      char_length(vc_kor_full),
      char_length(vc_eng_full),
      char_length(vc_spc_full),
      char_length(vc2_kor),
      char_length(vc2_eng),
      char_length(vc2_spc),
      char_length(vc2_kor_full),
      char_length(vc2_eng_full),
      char_length(vc2_spc_full),
      char_length(nvc_kor),
      char_length(nvc_eng),
      char_length(nvc_spc),
      char_length(nvc_kor_full),
      char_length(nvc_eng_full),
      char_length(nvc_spc_full),
      char_length(nvc2_kor),
      char_length(nvc2_eng),
      char_length(nvc2_spc),
      char_length(nvc2_kor_full),
      char_length(nvc2_eng_full),
      char_length(nvc2_spc_full)
    FROM string_test_table',
    $$VALUES (
      1::INTEGER,
      1::INTEGER,
      1::INTEGER,
      14::INTEGER,
      26::INTEGER,
      16::INTEGER,
      1::INTEGER,
      1::INTEGER,
      1::INTEGER,
      14::INTEGER,
      26::INTEGER,
      16::INTEGER,
      1::INTEGER,
      1::INTEGER,
      1::INTEGER,
      14::INTEGER,
      26::INTEGER,
      16::INTEGER,
      1::INTEGER,
      1::INTEGER,
      1::INTEGER,
      14::INTEGER,
      26::INTEGER,
      16::INTEGER,
      1::INTEGER,
      1::INTEGER,
      1::INTEGER,
      14::INTEGER,
      26::INTEGER,
      16::INTEGER,
      1::INTEGER,
      1::INTEGER,
      1::INTEGER,
      14::INTEGER,
      26::INTEGER,
      16::INTEGER)
    $$
  );

  -- TEST 4: lower() 함수
  SELECT results_eq('
    SELECT
      lower(c_kor),
      lower(c_eng),
      lower(c_spc),
      lower(c_kor_full),
      lower(c_eng_full),
      lower(c_spc_full),
      lower(nc_kor),
      lower(nc_eng),
      lower(nc_spc),
      lower(nc_kor_full),
      lower(nc_eng_full),
      lower(nc_spc_full),
      lower(vc_kor),
      lower(vc_eng),
      lower(vc_spc),
      lower(vc_kor_full),
      lower(vc_eng_full),
      lower(vc_spc_full),
      lower(vc2_kor),
      lower(vc2_eng),
      lower(vc2_spc),
      lower(vc2_kor_full),
      lower(vc2_eng_full),
      lower(vc2_spc_full),
      lower(nvc_kor),
      lower(nvc_eng),
      lower(nvc_spc),
      lower(nvc_kor_full),
      lower(nvc_eng_full),
      lower(nvc_spc_full),
      lower(nvc2_kor),
      lower(nvc2_eng),
      lower(nvc2_spc),
      lower(nvc2_kor_full),
      lower(nvc2_eng_full),
      lower(nvc2_spc_full)
    FROM string_test_table',
    $$VALUES (
      '가'::TEXT,
      'a'::TEXT,
      '!'::TEXT,
      '가나다라마바사아자차카타파하'::TEXT,
      'abcdefghijklmnopqrstuvwxyz'::TEXT,
      '!@#$%^&*()<>/\\'''::TEXT,
      '가'::TEXT,
      'a'::TEXT,
      '!'::TEXT,
      '가나다라마바사아자차카타파하'::TEXT,
      'abcdefghijklmnopqrstuvwxyz'::TEXT,
      '!@#$%^&*()<>/\\'''::TEXT,
      '가'::TEXT,
      'a'::TEXT,
      '!'::TEXT,
      '가나다라마바사아자차카타파하'::TEXT,
      'abcdefghijklmnopqrstuvwxyz'::TEXT,
      '!@#$%^&*()<>/\\'''::TEXT,
      '가'::TEXT,
      'a'::TEXT,
      '!'::TEXT,
      '가나다라마바사아자차카타파하'::TEXT,
      'abcdefghijklmnopqrstuvwxyz'::TEXT,
      '!@#$%^&*()<>/\\'''::TEXT,
      '가'::TEXT,
      'a'::TEXT,
      '!'::TEXT,
      '가나다라마바사아자차카타파하'::TEXT,
      'abcdefghijklmnopqrstuvwxyz'::TEXT,
      '!@#$%^&*()<>/\\'''::TEXT,
      '가'::TEXT,
      'a'::TEXT,
      '!'::TEXT,
      '가나다라마바사아자차카타파하'::TEXT,
      'abcdefghijklmnopqrstuvwxyz'::TEXT,
      '!@#$%^&*()<>/\\'''::TEXT)
    $$
  );

  -- TEST 5: octet_length() 함수
  SELECT results_eq('
    SELECT
      octet_length(c_kor),
      octet_length(c_eng),
      octet_length(c_spc),
      octet_length(c_kor_full),
      octet_length(c_eng_full),
      octet_length(c_spc_full),
      octet_length(nc_kor),
      octet_length(nc_eng),
      octet_length(nc_spc),
      octet_length(nc_kor_full),
      octet_length(nc_eng_full),
      octet_length(nc_spc_full),
      octet_length(vc_kor),
      octet_length(vc_eng),
      octet_length(vc_spc),
      octet_length(vc_kor_full),
      octet_length(vc_eng_full),
      octet_length(vc_spc_full),
      octet_length(vc2_kor),
      octet_length(vc2_eng),
      octet_length(vc2_spc),
      octet_length(vc2_kor_full),
      octet_length(vc2_eng_full),
      octet_length(vc2_spc_full),
      octet_length(nvc_kor),
      octet_length(nvc_eng),
      octet_length(nvc_spc),
      octet_length(nvc_kor_full),
      octet_length(nvc_eng_full),
      octet_length(nvc_spc_full),
      octet_length(nvc2_kor),
      octet_length(nvc2_eng),
      octet_length(nvc2_spc),
      octet_length(nvc2_kor_full),
      octet_length(nvc2_eng_full),
      octet_length(nvc2_spc_full)
    FROM string_test_table',
    $$VALUES (
      102::INTEGER,
      100::INTEGER,
      100::INTEGER,
      2028::INTEGER,
      2000::INTEGER,
      2000::INTEGER,
      102::INTEGER,
      100::INTEGER,
      100::INTEGER,
      2028::INTEGER,
      2000::INTEGER,
      2000::INTEGER,
      3::INTEGER,
      1::INTEGER,
      1::INTEGER,
      42::INTEGER,
      26::INTEGER,
      16::INTEGER,
      3::INTEGER,
      1::INTEGER,
      1::INTEGER,
      42::INTEGER,
      26::INTEGER,
      16::INTEGER,
      3::INTEGER,
      1::INTEGER,
      1::INTEGER,
      42::INTEGER,
      26::INTEGER,
      16::INTEGER,
      3::INTEGER,
      1::INTEGER,
      1::INTEGER,
      42::INTEGER,
      26::INTEGER,
      16::INTEGER)
    $$
  );

  -- TEST 6: overlay() 함수
  SELECT results_eq('
    SELECT
      overlay(c_kor placing ''하'' from 1 for 2), c_kor,
      overlay(c_eng placing ''z'' from 1 for 2), c_eng,
      overlay(c_spc placing ''+'' from 1 for 2), c_spc,
      overlay(c_kor_full placing ''하'' from 1 for 7), c_kor_full,
      overlay(c_eng_full placing ''z'' from 1 for 7), c_eng_full,
      overlay(c_spc_full placing ''+'' from 1 for 7), c_spc_full,
      overlay(nc_kor placing ''하'' from 1 for 2), nc_kor,
      overlay(nc_eng placing ''z'' from 1 for 2), nc_eng,
      overlay(nc_spc placing ''+'' from 1 for 2), nc_spc,
      overlay(nc_kor_full placing ''하'' from 1 for 7), nc_kor_full,
      overlay(nc_eng_full placing ''z'' from 1 for 7), nc_eng_full,
      overlay(nc_spc_full placing ''+'' from 1 for 7), nc_spc_full,
      overlay(vc_kor placing ''하'' from 1 for 2), vc_kor,
      overlay(vc_eng placing ''z'' from 1 for 2), vc_eng,
      overlay(vc_spc placing ''+'' from 1 for 2), vc_spc,
      overlay(vc_kor_full placing ''하'' from 1 for 7), vc_kor_full,
      overlay(vc_eng_full placing ''z'' from 1 for 7), vc_eng_full,
      overlay(vc_spc_full placing ''+'' from 1 for 7), vc_spc_full,
      overlay(vc2_kor placing ''하'' from 1 for 2), vc2_kor,
      overlay(vc2_eng placing ''z'' from 1 for 2), vc2_eng,
      overlay(vc2_spc placing ''+'' from 1 for 2), vc2_spc,
      overlay(vc2_kor_full placing ''하'' from 1 for 7), vc2_kor_full,
      overlay(vc2_eng_full placing ''z'' from 1 for 7), vc2_eng_full,
      overlay(vc2_spc_full placing ''+'' from 1 for 7), vc2_spc_full,
      overlay(nvc_kor placing ''하'' from 1 for 2), nvc_kor,
      overlay(nvc_eng placing ''z'' from 1 for 2), nvc_eng,
      overlay(nvc_spc placing ''+'' from 1 for 2), nvc_spc,
      overlay(nvc_kor_full placing ''하'' from 1 for 7), nvc_kor_full,
      overlay(nvc_eng_full placing ''z'' from 1 for 7), nvc_eng_full,
      overlay(nvc_spc_full placing ''+'' from 1 for 7), nvc_spc_full,
      overlay(nvc2_kor placing ''하'' from 1 for 2), nvc2_kor,
      overlay(nvc2_eng placing ''z'' from 1 for 2), nvc2_eng,
      overlay(nvc2_spc placing ''+'' from 1 for 2), nvc2_spc,
      overlay(nvc2_kor_full placing ''하'' from 1 for 7), nvc2_kor_full,
      overlay(nvc2_eng_full placing ''z'' from 1 for 7), nvc2_eng_full,
      overlay(nvc2_spc_full placing ''+'' from 1 for 7) nvc2_spc_full
    FROM string_test_table',
    $$VALUES (
      '하'::TEXT,
      '가'::CHAR(100),
      'z'::TEXT,
      'a'::CHAR(100),
      '+'::TEXT,
      '!'::CHAR(100),
      '하아자차카타파하'::TEXT,
      '가나다라마바사아자차카타파하'::CHAR(2000),
      'zhijklmnopqrstuvwxyz'::TEXT,
      'abcdefghijklmnopqrstuvwxyz'::CHAR(2000),
      '+*()<>/\\'''::TEXT,
      '!@#$%^&*()<>/\\'''::CHAR(2000),
      '하'::TEXT,
      '가'::NCHAR(100),
      'z'::TEXT,
      'a'::NCHAR(100),
      '+'::TEXT,
      '!'::NCHAR(100),
      '하아자차카타파하'::TEXT,
      '가나다라마바사아자차카타파하'::NCHAR(2000),
      'zhijklmnopqrstuvwxyz'::TEXT,
      'abcdefghijklmnopqrstuvwxyz'::NCHAR(2000),
      '+*()<>/\\'''::TEXT,
      '!@#$%^&*()<>/\\'''::NCHAR(2000),
      '하'::TEXT,
      '가'::VARCHAR,
      'z'::TEXT,
      'a'::VARCHAR,
      '+'::TEXT,
      '!'::VARCHAR,
      '하아자차카타파하'::TEXT,
      '가나다라마바사아자차카타파하'::VARCHAR,
      'zhijklmnopqrstuvwxyz'::TEXT,
      'abcdefghijklmnopqrstuvwxyz'::VARCHAR,
      '+*()<>/\\'''::TEXT,
      '!@#$%^&*()<>/\\'''::VARCHAR,
      '하'::TEXT,
      '가'::VARCHAR,
      'z'::TEXT,
      'a'::VARCHAR,
      '+'::TEXT,
      '!'::VARCHAR,
      '하아자차카타파하'::TEXT,
      '가나다라마바사아자차카타파하'::VARCHAR,
      'zhijklmnopqrstuvwxyz'::TEXT,
      'abcdefghijklmnopqrstuvwxyz'::VARCHAR,
      '+*()<>/\\'''::TEXT,
      '!@#$%^&*()<>/\\'''::VARCHAR,
      '하'::TEXT,
      '가'::TEXT,
      'z'::TEXT,
      'a'::TEXT,
      '+'::TEXT,
      '!'::TEXT,
      '하아자차카타파하'::TEXT,
      '가나다라마바사아자차카타파하'::TEXT,
      'zhijklmnopqrstuvwxyz'::TEXT,
      'abcdefghijklmnopqrstuvwxyz'::TEXT,
      '+*()<>/\\'''::TEXT,
      '!@#$%^&*()<>/\\'''::TEXT,
      '하'::TEXT,
      '가'::TEXT,
      'z'::TEXT,
      'a'::TEXT,
      '+'::TEXT,
      '!'::TEXT,
      '하아자차카타파하'::TEXT,
      '가나다라마바사아자차카타파하'::TEXT,
      'zhijklmnopqrstuvwxyz'::TEXT,
      'abcdefghijklmnopqrstuvwxyz'::TEXT,
      '+*()<>/\\'''::TEXT)
    $$
  );

  -- TEST 7: position() 함수
  SELECT results_eq('
    SELECT
      position(''가'' in c_kor),
      position(''a'' in c_eng),
      position(''!'' in c_spc),
      position(''사아'' in c_kor_full),
      position(''mn'' in c_eng_full),
      position(''()'' in c_spc_full),
      position(''가'' in nc_kor),
      position(''a'' in nc_eng),
      position(''!'' in nc_spc),
      position(''사아'' in nc_kor_full),
      position(''mn'' in nc_eng_full),
      position(''()'' in nc_spc_full),
      position(''가'' in vc_kor),
      position(''a'' in vc_eng),
      position(''!'' in vc_spc),
      position(''사아'' in vc_kor_full),
      position(''mn'' in vc_eng_full),
      position(''()'' in vc_spc_full),
      position(''가'' in vc2_kor),
      position(''a'' in vc2_eng),
      position(''!'' in vc2_spc),
      position(''사아'' in vc2_kor_full),
      position(''mn'' in vc2_eng_full),
      position(''()'' in vc2_spc_full),
      position(''가'' in nvc_kor),
      position(''a'' in nvc_eng),
      position(''!'' in nvc_spc),
      position(''사아'' in nvc_kor_full),
      position(''mn'' in nvc_eng_full),
      position(''()'' in nvc_spc_full),
      position(''가'' in nvc2_kor),
      position(''a'' in nvc2_eng),
      position(''!'' in nvc2_spc),
      position(''사아'' in nvc2_kor_full),
      position(''mn'' in nvc2_eng_full),
      position(''()'' in nvc2_spc_full)
    FROM string_test_table',
    $$VALUES (
      1::INTEGER,
      1::INTEGER,
      1::INTEGER,
      7::INTEGER,
      13::INTEGER,
      9::INTEGER,
      1::INTEGER,
      1::INTEGER,
      1::INTEGER,
      7::INTEGER,
      13::INTEGER,
      9::INTEGER,
      1::INTEGER,
      1::INTEGER,
      1::INTEGER,
      7::INTEGER,
      13::INTEGER,
      9::INTEGER,
      1::INTEGER,
      1::INTEGER,
      1::INTEGER,
      7::INTEGER,
      13::INTEGER,
      9::INTEGER,
      1::INTEGER,
      1::INTEGER,
      1::INTEGER,
      7::INTEGER,
      13::INTEGER,
      9::INTEGER,
      1::INTEGER,
      1::INTEGER,
      1::INTEGER,
      7::INTEGER,
      13::INTEGER,
      9::INTEGER)
    $$
  );

  -- TEST 8: substring() 함수
  SELECT results_eq('
    SELECT
      substring(c_kor from 0 for 1),
      substring(c_eng from 0 for 1),
      substring(c_spc from 0 for 1),
      substring(c_kor_full from 3 for 7),
      substring(c_eng_full from 3 for 7),
      substring(c_spc_full from 3 for 7),
      substring(nc_kor from 0 for 1),
      substring(nc_eng from 0 for 1),
      substring(nc_spc from 0 for 1),
      substring(nc_kor_full from 3 for 7),
      substring(nc_eng_full from 3 for 7),
      substring(nc_spc_full from 3 for 7),
      substring(vc_kor from 0 for 1),
      substring(vc_eng from 0 for 1),
      substring(vc_spc from 0 for 1),
      substring(vc_kor_full from 3 for 7),
      substring(vc_eng_full from 3 for 7),
      substring(vc_spc_full from 3 for 7),
      substring(vc2_kor from 0 for 1),
      substring(vc2_eng from 0 for 1),
      substring(vc2_spc from 0 for 1),
      substring(vc2_kor_full from 3 for 7),
      substring(vc2_eng_full from 3 for 7),
      substring(vc2_spc_full from 3 for 7),
      substring(nvc_kor from 0 for 1),
      substring(nvc_eng from 0 for 1),
      substring(nvc_spc from 0 for 1),
      substring(nvc_kor_full from 3 for 7),
      substring(nvc_eng_full from 3 for 7),
      substring(nvc_spc_full from 3 for 7),
      substring(nvc2_kor from 0 for 1),
      substring(nvc2_eng from 0 for 1),
      substring(nvc2_spc from 0 for 1),
      substring(nvc2_kor_full from 3 for 7),
      substring(nvc2_eng_full from 3 for 7),
      substring(nvc2_spc_full from 3 for 7)
    FROM string_test_table',
    $$VALUES (
      ''::TEXT,
      ''::TEXT,
      ''::TEXT,
      '다라마바사아자'::TEXT,
      'cdefghi'::TEXT,
      '#$%^&*('::TEXT,
      ''::TEXT,
      ''::TEXT,
      ''::TEXT,
      '다라마바사아자'::TEXT,
      'cdefghi'::TEXT,
      '#$%^&*('::TEXT,
      ''::TEXT,
      ''::TEXT,
      ''::TEXT,
      '다라마바사아자'::TEXT,
      'cdefghi'::TEXT,
      '#$%^&*('::TEXT,
      ''::TEXT,
      ''::TEXT,
      ''::TEXT,
      '다라마바사아자'::TEXT,
      'cdefghi'::TEXT,
      '#$%^&*('::TEXT,
      ''::TEXT,
      ''::TEXT,
      ''::TEXT,
      '다라마바사아자'::TEXT,
      'cdefghi'::TEXT,
      '#$%^&*('::TEXT,
      ''::TEXT,
      ''::TEXT,
      ''::TEXT,
      '다라마바사아자'::TEXT,
      'cdefghi'::TEXT,
      '#$%^&*('::TEXT)
    $$
  );

  -- TEST 9: trim() 함수
  SELECT results_eq('
    SELECT
      trim(both ''가'' from c_kor),
      trim(both ''a'' from c_eng),
      trim(both ''!'' from c_spc),
      trim(both ''가파다라하'' from c_kor_full),
      trim(both ''azbycx'' from c_eng_full),
      trim(both ''!\@#/'' from c_spc_full),
      trim(both ''가'' from nc_kor),
      trim(both ''a'' from nc_eng),
      trim(both ''!'' from nc_spc),
      trim(both ''가파다라하'' from nc_kor_full),
      trim(both ''azbycx'' from nc_eng_full),
      trim(both ''!\@#/'' from nc_spc_full),
      trim(both ''가'' from vc_kor),
      trim(both ''a'' from vc_eng),
      trim(both ''!'' from vc_spc),
      trim(both ''가파다라하'' from vc_kor_full),
      trim(both ''azbycx'' from vc_eng_full),
      trim(both ''!\@#/'' from vc_spc_full),
      trim(both ''가'' from vc2_kor),
      trim(both ''a'' from vc2_eng),
      trim(both ''!'' from vc2_spc),
      trim(both ''가파다라하'' from vc2_kor_full),
      trim(both ''azbycx'' from vc2_eng_full),
      trim(both ''!\@#/'' from vc2_spc_full),
      trim(both ''가'' from nvc_kor),
      trim(both ''a'' from nvc_eng),
      trim(both ''!'' from nvc_spc),
      trim(both ''가파다라하'' from nvc_kor_full),
      trim(both ''azbycx'' from nvc_eng_full),
      trim(both ''!\@#/'' from nvc_spc_full),
      trim(both ''가'' from nvc2_kor),
      trim(both ''a'' from nvc2_eng),
      trim(both ''!'' from nvc2_spc),
      trim(both ''가파다라하'' from nvc2_kor_full),
      trim(both ''azbycx'' from nvc2_eng_full),
      trim(both ''!\@#/'' from nvc2_spc_full)
    FROM string_test_table',
    $$VALUES (
      ''::TEXT,
      ''::TEXT,
      ''::TEXT,
      '나다라마바사아자차카타'::TEXT,
      'defghijklmnopqrstuvw'::TEXT,
      '$%^&*()<>/\\'''::TEXT,
      ''::TEXT,
      ''::TEXT,
      ''::TEXT,
      '나다라마바사아자차카타'::TEXT,
      'defghijklmnopqrstuvw'::TEXT,
      '$%^&*()<>/\\'''::TEXT,
      ''::TEXT,
      ''::TEXT,
      ''::TEXT,
      '나다라마바사아자차카타'::TEXT,
      'defghijklmnopqrstuvw'::TEXT,
      '$%^&*()<>/\\'''::TEXT,
      ''::TEXT,
      ''::TEXT,
      ''::TEXT,
      '나다라마바사아자차카타'::TEXT,
      'defghijklmnopqrstuvw'::TEXT,
      '$%^&*()<>/\\'''::TEXT,
      ''::TEXT,
      ''::TEXT,
      ''::TEXT,
      '나다라마바사아자차카타'::TEXT,
      'defghijklmnopqrstuvw'::TEXT,
      '$%^&*()<>/\\'''::TEXT,
      ''::TEXT,
      ''::TEXT,
      ''::TEXT,
      '나다라마바사아자차카타'::TEXT,
      'defghijklmnopqrstuvw'::TEXT,
      '$%^&*()<>/\\'''::TEXT)
    $$
  );

  -- TEST 10: upper() 함수
  SELECT results_eq('
    SELECT
      upper(c_kor),
      upper(c_eng),
      upper(c_spc),
      upper(c_kor_full),
      upper(c_eng_full),
      upper(c_spc_full),
      upper(nc_kor),
      upper(nc_eng),
      upper(nc_spc),
      upper(nc_kor_full),
      upper(nc_eng_full),
      upper(nc_spc_full),
      upper(vc_kor),
      upper(vc_eng),
      upper(vc_spc),
      upper(vc_kor_full),
      upper(vc_eng_full),
      upper(vc_spc_full),
      upper(vc2_kor),
      upper(vc2_eng),
      upper(vc2_spc),
      upper(vc2_kor_full),
      upper(vc2_eng_full),
      upper(vc2_spc_full),
      upper(nvc_kor),
      upper(nvc_eng),
      upper(nvc_spc),
      upper(nvc_kor_full),
      upper(nvc_eng_full),
      upper(nvc_spc_full),
      upper(nvc2_kor),
      upper(nvc2_eng),
      upper(nvc2_spc),
      upper(nvc2_kor_full),
      upper(nvc2_eng_full),
      upper(nvc2_spc_full)
    FROM string_test_table',
    $$VALUES (
      '가'::TEXT,
      'A'::TEXT,
      '!'::TEXT,
      '가나다라마바사아자차카타파하'::TEXT,
      'ABCDEFGHIJKLMNOPQRSTUVWXYZ'::TEXT,
      '!@#$%^&*()<>/\\'''::TEXT,
      '가'::TEXT,
      'A'::TEXT,
      '!'::TEXT,
      '가나다라마바사아자차카타파하'::TEXT,
      'ABCDEFGHIJKLMNOPQRSTUVWXYZ'::TEXT,
      '!@#$%^&*()<>/\\'''::TEXT,
      '가'::TEXT,
      'A'::TEXT,
      '!'::TEXT,
      '가나다라마바사아자차카타파하'::TEXT,
      'ABCDEFGHIJKLMNOPQRSTUVWXYZ'::TEXT,
      '!@#$%^&*()<>/\\'''::TEXT,
      '가'::TEXT,
      'A'::TEXT,
      '!'::TEXT,
      '가나다라마바사아자차카타파하'::TEXT,
      'ABCDEFGHIJKLMNOPQRSTUVWXYZ'::TEXT,
      '!@#$%^&*()<>/\\'''::TEXT,
      '가'::TEXT,
      'A'::TEXT,
      '!'::TEXT,
      '가나다라마바사아자차카타파하'::TEXT,
      'ABCDEFGHIJKLMNOPQRSTUVWXYZ'::TEXT,
      '!@#$%^&*()<>/\\'''::TEXT,
      '가'::TEXT,
      'A'::TEXT,
      '!'::TEXT,
      '가나다라마바사아자차카타파하'::TEXT,
      'ABCDEFGHIJKLMNOPQRSTUVWXYZ'::TEXT,
      '!@#$%^&*()<>/\\'''::TEXT)
    $$
  );

  -- Finish the tests and clean up.
  SELECT * FROM finish();

ROLLBACK;
